### ISSUE TITLE
Provide a way to disable long running tests on dev machines

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-fdt#13]
Running the regression tests for things such as overflows (see: https://github.com/rust-vmm/vm-fdt/blob/2e4ebdeb27be5b450b51b79fdeeeee3750d42182/src/writer.rs#L804) takes a really long time. This is not a good experience for development when you want to  quickly check if the changes you introduced don't add other problems. We should find a way to ignore those tests in development environments, and only run them with the CI.

One option might be to have these kind of tests under a feature since the CI runs the tests with all features enabled. This might be a bit awkward since it would a feature only used in tests. Having them with the `ignore` macro might not be a good option because it requires adding a specialized CI pipeline to run the ignored tests (or maybe this is a good option?). Are there any options here?

**Comment by danielverkamp** [comment]
Controlling it with a feature seems like a pretty reasonable method to me, but I'm not super familiar with how the rest of the Rust ecosystem handles tests like this.
