### ISSUE TITLE
Check that mem_reservations are valid

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-fdt#5]
The Devicetree spec says that the memory reservations regions [must not overlap](https://devicetree-specification.readthedocs.io/en/stable/flattened-format.html#format).

Should we add a check for this as well to be compliant with the specification? I am not sure if the kernel is checking that as well, but it sounds like we can exit early on errors.

@danielverkamp what do you think?

**Comment by danielverkamp** [comment]
Sounds reasonable to me - we don't fill in the reserve map for crosvm, and this parameter was mostly added for completeness, so it probably has some rough edges.  Maybe we can sort the regions inside `new` to make the overlap checks simpler? (I don't think the order is meaningful, so we should be free to reorder them.)

**Comment by andreeaflorescu** [comment]
Sounds good to me.
